### ISSUE TITLE
mobile version of member login link is broken

### ISSUE THREAD

**Issue by gjchen12** [WalkBikeCupertino/v2.0#1]
[Jian] 8/5/2016: I put a line in header.php to add the link, which works on computer, but not on the phone. Maybe it's too small?

**Comment by jianhe7** [comment]
Enlarged the member login in the top-header section to make it more click-able by hand.

**Comment by jianhe7** [comment]
in Divi-child/style.css:

 /\* enlarge the top-header on small screens and diplay social icons*/
@media (max-width: 981px) {
  #top-header {
    min-height: 40px;
  }
  #member-login {
    padding-top: 15px;
  }
  #top-header #et-secondary-menu {
    display: block !important;
    padding-top: 15px;
    float: right;
  }
}
