### ISSUE TITLE
Sync latest news, events to new website before launch

### ISSUE THREAD

**Issue by gjchen12** [WalkBikeCupertino/v2.0#12]
[Dick 7/31/2016] In Larry's news item of July 20, http://www.walkbikecupertino.org/wbc/?p=976 which appears as the first item under "Latest News" on the V1 home page , most of the text is repeated starting at "Stillman, Gerry Tallinger, ..."  The repeated text should be deleted.

This Post does not appear in V2 in the section, wbc-news/ Recent Posts.  At least, I am unable to find a link on V2 to "Latest News".   It will take time for me to get used to the new layout and be able to find things.

**Comment by jianhe7** [comment]
Removed repeated words for July 20th posting. 

Synced all events/venues/organizers from the old sites.

**Comment by jianhe7** [comment]
Limitation of the event calendar plugin to incrementally import the events:

https://theeventscalendar.com/support/forums/topic/duplicate-events-10/
